FIND_PROGRAM( VALGRIND_EXECUTABLE valgrind )
IF( VALGRIND_EXECUTABLE )
#  SET( MEMCHECK ${VALGRIND_EXECUTABLE} --leak-check=full --show-leak-kinds=all --num-callers=30 )
  SET( MEMCHECK ${VALGRIND_EXECUTABLE} --leak-check=full --num-callers=30 )
ENDIF( VALGRIND_EXECUTABLE )
SET( ENV{OY_MODULE_PATH} "${CMAKE_BINARY_DIR}/../../src/modules" )
EXECUTE_PROCESS( COMMAND echo "./test_core" )
EXECUTE_PROCESS( COMMAND ./test_core )
EXECUTE_PROCESS( COMMAND echo "./test_core-static" )
EXECUTE_PROCESS( COMMAND ${MEMCHECK} ./test_core-static )
EXECUTE_PROCESS( COMMAND echo "./test_object" )
EXECUTE_PROCESS( COMMAND ./test_object )
EXECUTE_PROCESS( COMMAND echo "./test_object-static" )
EXECUTE_PROCESS( COMMAND ${MEMCHECK} ./test_object-static )
EXECUTE_PROCESS( COMMAND echo "./test_modules" )
EXECUTE_PROCESS( COMMAND ${MEMCHECK} ./test_modules )
EXECUTE_PROCESS( COMMAND echo "./test_config" )
EXECUTE_PROCESS( COMMAND ./test_config )
EXECUTE_PROCESS( COMMAND echo "./test_oyranos" )
EXECUTE_PROCESS( COMMAND ./test_oyranos )
EXECUTE_PROCESS( COMMAND echo "./test_oyranos-static" )
EXECUTE_PROCESS( COMMAND ./test_oyranos-static )
