SET( ENV{OY_MODULE_PATH} "../.." )
EXECUTE_PROCESS( COMMAND echo "./test_core")
EXECUTE_PROCESS( COMMAND ./test_core)
EXECUTE_PROCESS( COMMAND echo "./test_core-static")
EXECUTE_PROCESS( COMMAND ./test_core-static)
EXECUTE_PROCESS( COMMAND echo "./test_object")
EXECUTE_PROCESS( COMMAND ./test_object)
EXECUTE_PROCESS( COMMAND echo "./test_object-static")
EXECUTE_PROCESS( COMMAND ./test_object-static)
EXECUTE_PROCESS( COMMAND echo "./test_modules")
EXECUTE_PROCESS( COMMAND ./test_modules)
EXECUTE_PROCESS( COMMAND echo "./test_modules-static")
EXECUTE_PROCESS( COMMAND ./test_modules-static)
EXECUTE_PROCESS( COMMAND echo "./test_config")
EXECUTE_PROCESS( COMMAND ./test_config)
EXECUTE_PROCESS( COMMAND echo "./test_config-static")
EXECUTE_PROCESS( COMMAND ./test_config-static)
EXECUTE_PROCESS( COMMAND echo "./test_oyranos")
EXECUTE_PROCESS( COMMAND ./test_oyranos)
EXECUTE_PROCESS( COMMAND echo "./test_oyranos-static")
EXECUTE_PROCESS( COMMAND ./test_oyranos-static)
