.TH "oyranos-policy" 1 "February 20, 2007" "User Commands"
.SH NAME
oyranos-policy \- Oyranos CMS policy tool
.SH SYNOPSIS
.B oyranos-policy
.SH DESCRIPTION
The tool dumps out / read a configuration of the Oyranos colour management system (CMS).
.SH OPTIONS
.TP
.B oyranos_settings_file_name
must be in Oyranos own xml-ish text format
.SH EXAMPLES
.TP
Set new policy:
.B oyranos-policy policy_filename
.TP
Dump the current policy:
.B oyranos-policy
.PP
.SH AUTHOR
Kai-Uwe Behrmann (ku.b (at) gmx.de)
.SH "SEE ALSO"
oyranos-config(1) oyranos-policy(1) oyranos-monitor(1) oyranos(3)
.SH BUGS
at: http://sourceforge.net/tracker/?group_id=177017&atid=879553
