.TH oyranos-monitor 1 "Mai 20, 2009" "User Commands"
.SH NAME
oyranos-monitor \- Oyranos CMS monitor configuration
.SH SYNOPSIS
\fBoyranos-monitor\fR [ |-s [-x num] [-y num] [-v] ]
.fi 
\fBoyranos-monitor\fR [ -x num -y num  profilename [-v] ]
.fi 
\fBoyranos-monitor\fR [ -b [-x num] [-y num] [-v] ]
.fi 
\fBoyranos-monitor\fR [ -e [-x num] [-y num] [-v] ]
.fi 
\fBoyranos-monitor\fR [ -l [-v] ]
.SH DESCRIPTION
This little programm let you query and set the monitor profile(s) within the Oyranos colour management system (CMS).
.SH OPTIONS
.TP
\fB\-x\fR=\fIPOSITION\fR
select the display at the x position
.TP
\fB\-y\fR=\fIPOSITION\fR
select the display at the y position
.TP
.B \-s, \-\-setup \fR[default] [-x] [-y]
Set up the X11 server with the Oyranos DB stored monitor ICC profile(s)
.TP
.B \-e, \-\-unset \fR[-x] [-y]
reset one hardware gamma table to the defaults
.TP
.B \-b, \-\-database \fR[-x] [-y]
query one profile name from the Oyranos device profile data base
.TP
.B \-l, \-\-list
list devices visible to Oyranos
.TP
.B \-v, \-\-verbose
increase verbosity
.SH ENVIRONMENT
.TP
.B DISPLAY
on X11 systems the display is selected by this variable
.TP
.B OYRANOS_DEBUG
set the Oyranos debug level. Alternatively the -v option can be used.
.TP
.B XDG_DATA_HOME XDG_DATA_DIRS
http://www.oyranos.com/wiki/index.php?title=OpenIccDirectoryProposal
.SH EXAMPLES 
.TP
Put the following in a setup script like .xinitrc:
.nf
# select a monitor profile, load the binary blob into X and
# fill the VideoCardGammaTable, if appropriate
.fi
.B oyranos-monitor
.PP 
.TP
Assign a ICC profile to a screen:
.B oyranos-monitor -x pos -y pos  profilename
.PP 
.TP
Reset a screens hardware LUT in order to do a calibration:
.B oyranos-monitor -e -x pos -y pos  profilename
.PP 
.TP
Query the server side, network transparent profile:
.B oyranos-monitor -x pos -y pos
.PP 
.TP
Query the Oyranos device data base profile on the local computer:
.B oyranos-monitor -b -x pos -y pos
.PP 
.TP
List all Oyranos monitor devices:
.B oyranos-monitor -l
.PP 
.SH AUTHOR
Kai-Uwe Behrmann (ku.b (at) gmx.de)
.SH COPYRIGHT
(c) 2005-2009, Kai-Uwe Behrmann
.fi
License: new BSD <http://www.opensource.org/licenses/bsd-license.php>
.SH "SEE ALSO"
oyranos-config-fltk(1) oyranos-policy(1) oyranos(3)
.fi
http://www.oyranos.org
.SH "REPORTING BUGS"
at: http://sourceforge.net/tracker/?group_id=177017&atid=879553
