.TH oyranos-monitor-nvidia 1 "July 09, 2011" "User Commands"
.SH NAME
oyranos-monitor-nvidia \- Oyranos CMS nvidia monitor configuration
.SH SYNOPSIS
\fBoyranos-monitor-nvidia\fR [ -n [-v] ]
.fi
\fBoyranos-monitor-nvidia\fR [ -s pos [-v] ]
.fi
\fBoyranos-monitor-nvidia\fR [ -p [-v] ]
.fi
\fBoyranos-monitor-nvidia\fR [ -h ]
.SH DESCRIPTION
The oyranos-monitor-nvidia tool uses nvidia specific APIs and prepares EDID information from propriarity nvidia drivers, where XRandR is not available with Xorg.
.SH OPTIONS
.TP
.B \-n , \-\-number
the number of available screens
.TP
.B \-p , \-\-put
put the edid info into the root window
.TP
\fB\-s\fR=\fISCREEN\fR , \-s\fR \fISCREEN\fR , \-\-screen\fR \fISCREEN\fR 
select the screen by number
.TP
.B \-v, \-\-verbose
increase verbosity
.TP
.B \-h
show a help text
.SH ENVIRONMENT
.TP
.B DISPLAY
On X11 systems the display is selected by this variable.
.TP
.B OYRANOS_DEBUG
set the Oyranos debug level. Alternatively the -v option can be used.
.TP
.B XDG_DATA_HOME XDG_DATA_DIRS
route Oyranos to top directories containing resources. The derived paths for
ICC profiles have a "color/icc" appended.
.nf
http://www.oyranos.com/wiki/index.php?title=OpenIccDirectoryProposal
.TP
.B OY_MODULE_PATHS
route Oyranos to additional directories containing modules.
.SH EXAMPLES
.TP
Show available informations:
.B oyranos-monitor-nvidia
.PP
.TP
Put the EDID informations into the root window for Oyranos:
.B oyranos-monitor-nvidia -p
.PP
.SH AUTHOR
Kai-Uwe Behrmann (ku.b (at) gmx.de)
.SH COPYRIGHT
(c) 2005-2011, Kai-Uwe Behrmann and others
.fi
License: new BSD <http://www.opensource.org/licenses/bsd-license.php>
.SH "SEE ALSO"
oyranos-monitor(1) oyranos(3)
.fi
http://www.oyranos.org
.SH "REPORTING BUGS"
at: http://sourceforge.net/tracker/?group_id=177017&atid=879553
