.TH "openicc-device" 1 "" "User Commands"
.SH NAME
openicc-device v0.1.1 \- OpenICC Device
.SH ÜBERSICHT
\fBopenicc-device\fR \fB\-l\fR [\fB\-d\fR \fINUMMER\fR] [\fB\-j\fR] [\fB\-n\fR] [\fB\-b\fR \fIDATEINAME\fR] [\fB\-v\fR]
.br
\fBopenicc-device\fR \fB\-a\fR \fB\-f\fR \fIDATEINAME\fR [\fB\-b\fR \fIDATEINAME\fR] [\fB\-v\fR]
.br
\fBopenicc-device\fR \fB\-e\fR \fB\-d\fR \fINUMMER\fR [\fB\-b\fR \fIDATEINAME\fR] [\fB\-v\fR]
.br
\fBopenicc-device\fR \fB\-p\fR [\fB\-s\fR] [\fB\-v\fR]
.br
\fBopenicc-device\fR \fB\-h\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR [\fB\-v\fR]
.SH BESCHREIBUNG
Bearbeitung von Geräteeinträgen in der Datenbank für OpenICC Farbmanagement
.SH OPTIONEN
.SS
Zeige die Geräte aus der DB
\fBopenicc-device\fR \fB\-l\fR [\fB\-d\fR \fINUMMER\fR] [\fB\-j\fR] [\fB\-n\fR] [\fB\-b\fR \fIDATEINAME\fR] [\fB\-v\fR]
.br
\fB\-l\fR|\fB\-\-list-devices\fR	Zeige Geräte
.br
\fB\-d\fR|\fB\-\-device\fR \fINUMMER\fR	Gerätebeposition (NUMMER:0 [≥0 ≤100 Δ1])
.br
\fB\-j\fR|\fB\-\-dump-json\fR	Schreibe OpenICC Json
.br
\fB\-n\fR|\fB\-\-long\fR	Zeige alle Schlüssel/Wertepaare
.br
\fB\-b\fR|\fB\-\-db-file\fR \fIDATEINAME\fR	DB Dateiname
.RS
Dateiname der OpenICC Json Gerätedatenbank
.RE
.SS
Trage Gerät in die DB ein
\fBopenicc-device\fR \fB\-a\fR \fB\-f\fR \fIDATEINAME\fR [\fB\-b\fR \fIDATEINAME\fR] [\fB\-v\fR]
.br
\fB\-a\fR|\fB\-\-add\fR	Trage Gerät in die DB ein
.br
\fB\-f\fR|\fB\-\-file-name\fR \fIDATEINAME\fR	Dateiname
.RS
Der Dateiname des OpenICC Gerätes im Json Format.
.RE
\fB\-b\fR|\fB\-\-db-file\fR \fIDATEINAME\fR	DB Dateiname
.RS
Dateiname der OpenICC Json Gerätedatenbank
.RE
.SS
Lösche Gerät von der DB
\fBopenicc-device\fR \fB\-e\fR \fB\-d\fR \fINUMMER\fR [\fB\-b\fR \fIDATEINAME\fR] [\fB\-v\fR]
.br
\fB\-e\fR|\fB\-\-erase-device\fR	Lösche Geräte
.br
\fB\-d\fR|\fB\-\-device\fR \fINUMMER\fR	Gerätebeposition (NUMMER:0 [≥0 ≤100 Δ1])
.br
\fB\-b\fR|\fB\-\-db-file\fR \fIDATEINAME\fR	DB Dateiname
.RS
Dateiname der OpenICC Json Gerätedatenbank
.RE
.SS
Zeige den Dateipfad zur DB
\fBopenicc-device\fR \fB\-p\fR [\fB\-s\fR] [\fB\-v\fR]
.br
\fB\-p\fR|\fB\-\-show-path\fR	Zeige Pfad
.br
\fB\-s\fR|\fB\-\-system\fR	Lokales System
.br
.SS
Allgemeine Optionen
\fBopenicc-device\fR \fB\-h\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR [\fB\-v\fR]
.br
\fB\-b\fR|\fB\-\-db-file\fR \fIDATEINAME\fR	DB Dateiname
.RS
Dateiname der OpenICC Json Gerätedatenbank
.RE
\fB\-X\fR|\fB\-\-export\fR \fIjson|json+command|man|markdown\fR	Exportiere formatierten Text
.RS
Hole Benutzerschnittstelle als Text
.RE
	\fB\-X\fR man		# Handbuch : Unix Handbuchseite - Hole Unix Handbuchseite
.br
	\fB\-X\fR markdown		# Markdown : Formatierter Text - Hole formatierten Text
.br
	\fB\-X\fR json		# Json : GUI - Hole Oyjl Json Benutzerschnittstelle
.br
	\fB\-X\fR json+command		# Json + Kommando : GUI + Kommando - Hole Oyjl Json Benutzerschnittstelle mit Kommando
.br
	\fB\-X\fR export		# Export : Alle verfügbaren Daten - Erhalte Daten für Entwickler
.br
\fB\-v\fR|\fB\-\-verbose\fR	plaudernd
.br
\fB\-h\fR|\fB\-\-help\fR	Hilfe
.br
.SH AUTOR
Kai-Uwe Behrmann http://www.openicc.org
.SH KOPIERRECHT
Copyright 2018 Kai-Uwe Behrmann
.br
Lizenz: newBSD http://www.openicc.org
.SH FEHLER
https://www.github.com/OpenICC/config/issues 

