.TH "oyranos-xforms-modules" 1 "July 08, 2011" "User Commands"
.SH NAME
oyranos-xforms-modules \- Oyranos command line option forms dumping tool
.SH SYNOPSIS
\fBoyranos-xforms-modules\fR [ [-n \fINAME\fR] [-x \fIFILENAME\fR] [-v] ]
.fi
\fBoyranos-xforms-modules\fR [-?]
.SH DESCRIPTION
The tool dumps out Oyranos option forms from a given module.
.SH OPTIONS
.TP
.B \-n \fImodule\fR
Get option forms from module.

\fB-f\fR include policy options

\fB-x\fR \fIFILENAME\fR
Write to a option forms document.

\fB-v\fR be verbose
.TP
.B \-?
help text
.SH ENVIRONMENT
.TP
.B OY_DEBUG
set the Oyranos debug level. Alternatively the -v option can be used.
.TP
.B XDG_CONFIG_HOME XDG_DATA_DIRS
route Oyranos to top directories containing resources. The derived paths for
policies have a "color/settings" appended.
.nf
http://www.oyranos.com/wiki/index.php?title=OpenIccDirectoryProposal
.TP
.B OY_MODULE_PATH
route Oyranos to additional directories containing modules.
.SH EXAMPLES
.TP
Get default options forms for module:
.B oyranos-xforms-modules -n lcm2
.TP
Get default options forms for module and write to a file:
.B oyranos-xforms-modules -n lcm2 -x lcms.xhtml
.TP
Pipe in forms, show and write to file:
.B oyranos-xforms-modules -n lcm2 | oyranos-xforms-fltk -o lcm2.xhtml
.TP
Print a help text:
.B oyranos-xforms-modules -?
.PP
.SH AUTHOR
Kai-Uwe Behrmann (ku.b (at) gmx.de)
.SH COPYRIGHT
(c) 2005-2011, Kai-Uwe Behrmann and others
.fi
License: new BSD <http://www.opensource.org/licenses/bsd-license.php>
.SH "SEE ALSO"
oyranos-config(3) oyranos-policy(1) oyranos(3) oyranos-xforms(1) oyranos-xforms-fltk(1)
.fi
http://www.oyranos.org
.SH "BUGS"
at: http://sourceforge.net/tracker/?group_id=177017&atid=879553
