
/* exported_symbols.c generated by exportsymbols.sh */

#include "kdbbackend.h"
#include "kdbLibLoader.h"

/* Make the compiler happy */

extern int libelektra_filesys_LTX_kdbBackendFactory;

kdblib_symbol kdb_exported_syms[] =
{

	{"libelektra-filesys", NULL},
	{"kdbBackendFactory", &libelektra_filesys_LTX_kdbBackendFactory },

	{ NULL, NULL }
};
