.TH oyjl 1 "November 12, 2017" "User Commands"
.SH NAME
oyjl \- Light weight JSON parse and manipulation tool


.SH SYNOPSIS
\fBoyjl\fR [-j|-c|-k|-p|-s \fISTRING\fR] [-v] [-i \fIFILENAME\fR] [-x \fIPATH\fR]


.SH DESCRIPTION
The oyjl program can be used to parse, filter sub trees, select values and modify values in JSON texts.


.SH OPTIONS
.TP
.B \-j\fR Print JSON to std output.
This option requires a -i JSON FILENAME and a -x XPATH.

.TP
.B \-c\fR Print count of leafs in node.
This option requires a -i JSON FILENAME.

.TP
.B \-k\fR Print key name of node.
This option requires a -i JSON FILENAME.

.TP
.B \-p\fR Print all matching paths.
This option requires a -i JSON FILENAME and a -x XPATH.

.TP
.B \-s\fR Set a key name to a value.
This option requires a -i JSON FILENAME, a -x XPATH and a -s STRING.


.SH GENERAL OPTIONS
.TP
.B \-i\fR \fIFILENAME\fR, \-i\fR=\fIFILENAME\fR a file or stream
A JSON file name or a input stream like "stdin".

.TP
.B \-x\fR \fIXPATH\fR, \-x\fR=\fIXPATH\fR path specifier.
The path consists of slash '/' separated terms. Each term can be a key name
or a square bracketed index. A empty term is used for a search inside a tree.

.TP
.B \-v, \-\-verbose\fR increase verbosity


.SH EXAMPLES
.TP
Print a key value or sub tree:
.B oyjl -i text.json -x ///[0]

.TP
Print the number of keys:
.B oyjl -c -i text.json -x my/path/

.TP
Print a key name:
.B oyjl -k -i text.json -x ///[0]

.TP
Print all matching xpaths:
.B oyjl -p -i text.json -x //

.TP
Modify a key/value:
.B oyjl -i text.json -x my/path/to/key -s value


.SH AUTHOR
Kai-Uwe Behrmann (ku.b (at) gmx.de)

  
.SH COPYRIGHT
(c) 2017, Kai-Uwe Behrmann and others
.fi
License: MIT <http://www.opensource.org/licenses/MIT>

  
.SH "SEE ALSO"
https://codedocs.xyz/oyranos-cms/oyranos/group__oyjl.html


.SH "BUGS"
at: https://github.com/oyranos-cms/oyranos/issues
