.TH "oyjl-args" 1 "26. Juni 2019" "User Commands"
.SH NAME
oyjl-args v1.0.0 \- Benutzerschnittstellen nach Quelltext
.SH ÜBERSICHT
\fBoyjl-args\fR \fB\-i\fR \fIDATEINAME\fR [\fB\-v\fR]
.br
\fBoyjl-args\fR \fB\-h\fR [\fB\-v\fR]
.SH BESCHREIBUNG
Werkzeug um Benutzerschnittstellen in JSON von *-X export* nach Quelltext zu übertragen.
.SH OPTIONEN
.SS
Erzeuge Quelltext
\fBoyjl-args\fR \fB\-i\fR \fIDATEINAME\fR [\fB\-v\fR]
.br
\fB\-i\fR|\fB\-\-input\fR \fIDATEINAME\fR	Setze Eingabe
.br
.SS
Allgemeine Optionen
\fBoyjl-args\fR \fB\-h\fR [\fB\-v\fR]
.br
\fB\-h\fR|\fB\-\-help\fR	Hilfe
.br
\fB\-v\fR|\fB\-\-verbose\fR	plaudernd
.br
.SH SIEHE AUCH
.TP
oyjl(1) oyjl-translate(1) oyjl-args-qml(1)
.br
https://codedocs.xyz/oyranos-cms/oyranos/group__oyjl.html
.SH AUTOR
Kai-Uwe Behrmann http://www.oyranos.org
.SH KOPIERRECHT
Copyright © 2017-2020 Kai-Uwe Behrmann
.br
Lizenz: newBSD http://www.oyranos.org
.SH FEHLER
https://www.github.com/oyranos-cms/oyranos/issues 

