.TH "oyranos-config-fltk" 1 "April 05, 2017" "User Commands"
.SH NAME
oyranos-config-fltk \- Oyranos CMS configuration panel
.SH SYNOPSIS
.B oyranos-config-fltk
.SH DESCRIPTION
The dialog lets you access most of the Oyranos color management system (CMS) dynamic informations.
.SH OPTIONS
.TP
.B none
.SH EXAMPLES
.TP
www.oyranos.org/wiki/index.php?title=Oyranos_Configuration_Dialog
.PP
.SH AUTHOR
Kai-Uwe Behrmann (ku.b (at) gmx.de)
.SH "SEE ALSO"
oyranos-config(3) oyranos-config-synnefo(1) oyranos-policy(1) oyranos-monitor(1) oyranos(3)
.SH BUGS
at: https://gitlab.com/oyranos/oyranos/issues
