.TH "oyranos-profiles" 1 "October 11, 2018" "User Commands"
.SH NAME
oyranos-profiles v0.9.7 \- Oyranos Profiles
.SH SYNOPSIS
\fBoyranos-profiles\fR \-l [\-f] [\-e] [\-a] [\-c] [\-d] [\-k] [\-n] [\-o] [\-i] [\-2] [\-4] [\-P] [\-T \fIKEY;VALUE\fR] [\-v]
.br
\fBoyranos-profiles\fR \-p [\-u|\-s|\-y|\-m] [\-v]
.br
\fBoyranos-profiles\fR \-I \fIICC_PROFILE\fR | \-t \fITAXI_ID\fR [\-u|\-s|\-y|\-m] [\-g] [\-v]
.br
\fBoyranos-profiles\fR \-h \-X \fIjson|json+command|man|markdown\fR
.SH DESCRIPTION
The tool can list installed profiles, search paths and can help install a ICC color profile in a search path.
.SH OPTIONS
.SS
List of available ICC color profiles
\fBoyranos-profiles\fR \-l [\-f] [\-e] [\-a] [\-c] [\-d] [\-k] [\-n] [\-o] [\-i] [\-2] [\-4] [\-P] [\-T \fIKEY;VALUE\fR] [\-v]
.br
\-l|\-\-list-profiles	List Profiles
.br
\-f|\-\-full-names	List profile full names
.RS
Show path name and file name.
.RE
\-e|\-\-internal-names	List profile internal names
.RS
The text string comes from the 'desc' tag.
.RE
\-a|\-\-abstract	Select Abstract profiles
.br
\-c|\-\-color-space	Select Color Space profiles
.br
\-d|\-\-display	Select Monitor profiles
.br
\-k|\-\-device-link	Select Device Link profiles
.br
\-n|\-\-named-color	Select Named Color profiles
.br
\-o|\-\-output	Select Output profiles
.br
\-i|\-\-input	Select Input profiles
.br
\-2|\-\-icc-version-2	Select ICC v2 Profiles
.br
\-4|\-\-icc-version-4	Select ICC v4 Profiles
.br
\-P|\-\-path	Show profiles containing a string as part of their full name
.RS
PATH_SUB_STRING
.RE
\-T|\-\-meta \fIKEY;VALUE\fR	Filter for meta tag key/value pair
.RS
Show profiles containing a certain key/value pair of their meta tag. VALUE can contain '*' to allow for substring matching.
.RE
\-D|\-\-duplicates	Show identical multiple installed profiles
.br
.SS
List search paths
\fBoyranos-profiles\fR \-p [\-u|\-s|\-y|\-m] [\-v]
.br
\-p|\-\-list-paths	List ICC Profile Paths
.br
\-u|\-\-user	User path
.br
\-s|\-\-system	System path
.br
\-y|\-\-oyranos	Oyranos path
.br
\-m|\-\-machine	Machine path
.br
.SS
Install Profile
\fBoyranos-profiles\fR \-I \fIICC_PROFILE\fR | \-t \fITAXI_ID\fR [\-u|\-s|\-y|\-m] [\-g] [\-v]
.br
\-I|\-\-install \fIICC_PROFILE\fR	Install Profile
.br
\-t|\-\-taxi \fITAXI_ID\fR	ICC Taxi Profile DB
.br
\-u|\-\-user	User path
.br
\-s|\-\-system	System path
.br
\-y|\-\-oyranos	Oyranos path
.br
\-m|\-\-machine	Machine path
.br
\-g|\-\-gui	Use Graphical User Interface
.br
.SS
General options
\fBoyranos-profiles\fR \-h \-X \fIjson|json+command|man|markdown\fR
.br
\-h|\-\-help	Help
.br
\-X|\-\-export \fIjson|json+command|man|markdown\fR	Export formated text
.RS
Get UI converted into text formats
.RE
	\-X man		# Man 
.br
	 Get a unix man page
.br
	\-X markdown		# Markdown 
.br
	 Get formated text
.br
	\-X json		# Json 
.br
	 Get a Oyjl Json UI declaration
.br
	\-X json+command		# Json + Command 
.br
	 Get Oyjl Json UI declaration incuding command
.br
	\-X export		# Export 
.br
	 Get UI data for developers
.br
\-r|\-\-no-repair	No Profile repair of ICC profile ID
.br
\-v|\-\-verbose	verbose
.br
.SH ENVIRONMENT VARIABLES
.TP
OY_DEBUG
.br
set the Oyranos debug level. Alternatively the -v option can be used. Valid integer range is from 1-20.
.TP
XDG_DATA_HOME XDG_DATA_DIRS
.br
route Oyranos to top directories containing resources. The derived paths for ICC profiles have a "color/icc" appended. http://www.oyranos.com/wiki/index.php?title=OpenIccDirectoryProposal  
.SH EXAMPLES
.TP
List all installed profiles by internal name
.br
oyranos-profiles -le 
.TP
List all installed profiles of the display and output device classes
.br
oyranos-profiles -l -od 
.TP
List all installed profiles in user path
.br
oyranos-profiles -lfu 
.TP
Install a profile for the actual user and show error messages in a GUI
.br
oyranos-profiles --install profilename -u --gui 
.TP
Install a profile for the actual user and show error messages in a GUI
.br
oyranos-profiles --install - --taxi=taxi_id/0 --gui -d -u 
.TP
Show file infos
.br
SAVEIFS=$IFS ; IFS=$'\n\b'; profiles=(`oyranos-profiles -ldf`); IFS=$SAVEIFS; for file in "${profiles[@]}"; do ls "$file"; done  
.SH AUTHOR
Kai-Uwe Behrmann http://www.oyranos.org
.SH COPYRIGHT
Copyright 2018 Kai-Uwe Behrmann
.br
License: newBSD
.SH BUGS
https://www.github.com/oyranos-cms/oyranos/issues 

