.TH "oyranos-policy" 1 "May 21, 2009" "User Commands"
.SH NAME
oyranos-policy \- Oyranos CMS policy tool
.SH SYNOPSIS
\fBoyranos-policy\fR [ [-c] [-v] ]
.fi
\fBoyranos-policy\fR [ [-d] [-v] ]
.fi
\fBoyranos-policy\fR [ [-i \fIFILENAME\fR] [-v] ]
.fi
\fBoyranos-policy\fR [ [-l] [-v] ]
.fi
\fBoyranos-policy\fR [ [-p] [-v] ]
.fi
\fBoyranos-policy\fR [ [-s \fIFILENAME\fR] [-v] ]
.fi
\fBoyranos-policy\fR [-h]
.SH DESCRIPTION
The tool dumps out / read a configuration of the Oyranos colour management system (CMS).
.SH OPTIONS
.TP
.B \-c
show current active policy name
.TP
.B \-d
dump out all settings in Oyranos' own xml-ish text format
.TP
.B \-i \fIFILENAME\fR
import;
FILENAME must be in Oyranos' own xml-ish text format
.TP
.B \-l
list available policies
.TP
.B \-p
list search paths
.TP
.B \-s \fIFILENAME\fR
Save and install to a new policy;
FILENAME must be in Oyranos' own xml-ish text format
.TP
.B \-l
help text
.SH ENVIRONMENT
.TP
.B OY_DEBUG
set the Oyranos debug level. Alternatively the -v option can be used.
.TP
.B XDG_CONFIG_HOME
route Oyranos to top directories containing resources. The derived paths for
policies have a "color/settings" appended.
.nf
http://www.oyranos.com/wiki/index.php?title=OpenIccDirectoryProposal
.SH EXAMPLES
.TP
Dump out the actual settings::
.B oyranos-policy -d
.TP
Set new policy:
.B oyranos-policy -i policy_filename
.TP
List available policies:
.B oyranos-policy -l
.TP
Currently active policy:
.B oyranos-policy -c
.TP
Save and install to a new policy:
.B oyranos-policy -s policy_name
.TP
Print a help text:
.B oyranos-policy -h
.PP
.SH AUTHOR
Kai-Uwe Behrmann (ku.b (at) gmx.de)
.SH COPYRIGHT
(c) 2005-2009, Kai-Uwe Behrmann
.fi
License: new BSD <http://www.opensource.org/licenses/bsd-license.php>
.SH "SEE ALSO"
oyranos-config(3) oyranos-monitor(1) oyranos(3)
.fi
http://www.oyranos.org
.SH "BUGS"
at: http://sourceforge.net/tracker/?group_id=177017&atid=879553
