.TH "oyranos-profile-graph" 1 "March 24, 2019" "User Commands"
.SH NAME
oyranos-profile-graph v0.9.7 \- Oyranos Profile Graph
.SH SYNOPSIS
\fBoyranos-profile-graph\fR [\-t \fINUMBER\fR] [\-b] [\-g] [\-w \fINUMBER\fR] [\-o \fI-|FILE\fR] [\-f \fIFORMAT\fR] [\-c] [\-x] [\-d \fINUMBER\fR] [\-n] [\-2] [\-4] [\-r] [\-v] ICC_PROFILES
.br
\fBoyranos-profile-graph\fR \-S [\-t \fINUMBER\fR] [\-b] [\-g] [\-w \fINUMBER\fR] [\-R] [\-o \fI-|FILE\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\fBoyranos-profile-graph\fR \-O [\-t \fINUMBER\fR] [\-b] [\-g] [\-w \fINUMBER\fR] [\-R] [\-o \fI-|FILE\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\fBoyranos-profile-graph\fR \-k \fINUMBER\fR [\-t \fINUMBER\fR] [\-b] [\-g] [\-w \fINUMBER\fR] [\-R] [\-o \fI-|FILE\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\fBoyranos-profile-graph\fR \-i \fISTRING\fR [\-t \fINUMBER\fR] [\-b] [\-g] [\-w \fINUMBER\fR] [\-R] [\-o \fI-|FILE\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\fBoyranos-profile-graph\fR \-s \fIFILE\fR [\-t \fINUMBER\fR] [\-b] [\-g] [\-w \fINUMBER\fR] [\-R] [\-o \fI-|FILE\fR] [\-f \fIFORMAT\fR|\-p \fIFORMAT\fR] [\-v]
.br
.SH DESCRIPTION
The  oyranos-profile-graph programm converts ICC profiles or embedded ICC profiles from images to a graph image. By default the program shows the saturation line of the specified profiles and writes to stdout.
.SH OPTIONS
.TP
2D Graph from profiles
\fBoyranos-profile-graph\fR [\-t \fINUMBER\fR] [\-b] [\-g] [\-w \fINUMBER\fR] [\-o \fI-|FILE\fR] [\-f \fIFORMAT\fR] [\-c] [\-x] [\-d \fINUMBER\fR] [\-n] [\-2] [\-4] [\-r] [\-v] ICC_PROFILES
.br
\-d|\-\-change-thickness \fINUMBER\fR	Specify increase of the thickness of the graph lines (NUMBER:0.7 [≥-1000 ≤1000])
.br
\-x|\-\-xyy	Use CIE*xyY *x*y plane for saturation line projection
.br
\-c|\-\-no-blackbody	Omit white line of lambert light emitters
.br
\-n|\-\-no-spectral-line	Omit the spectral line
.br
\-2|\-\-icc-version-2	Select ICC v2 Profiles
.br
\-4|\-\-icc-version-4	Select ICC v4 Profiles
.br
\-r|\-\-no-repair	No Profile repair of ICC profile ID
.br
.TP
Standard Observer 1931 2° Graph
\fBoyranos-profile-graph\fR \-S [\-t \fINUMBER\fR] [\-b] [\-g] [\-w \fINUMBER\fR] [\-R] [\-o \fI-|FILE\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\-S|\-\-standard-observer	CIE Standard Observer 1931 2°
.br
.TP
1964 10° Observer Graph
\fBoyranos-profile-graph\fR \-O [\-t \fINUMBER\fR] [\-b] [\-g] [\-w \fINUMBER\fR] [\-R] [\-o \fI-|FILE\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\-O|\-\-observer-64	CIE Observer 1964 10°
.br
.TP
Blackbody Radiator Spectrum Graph
\fBoyranos-profile-graph\fR \-k \fINUMBER\fR [\-t \fINUMBER\fR] [\-b] [\-g] [\-w \fINUMBER\fR] [\-R] [\-o \fI-|FILE\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\-k|\-\-kelvin \fINUMBER\fR	Blackbody Radiator (NUMBER:0 [≥0 ≤25000])
.br
.TP
Illuminant Spectrum Graph
\fBoyranos-profile-graph\fR \-i \fISTRING\fR [\-t \fINUMBER\fR] [\-b] [\-g] [\-w \fINUMBER\fR] [\-R] [\-o \fI-|FILE\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\-i|\-\-illuminant \fISTRING\fR	Illuminant Spectrum
.br
	\-i A		# Illuminant A  -  CIE A spectral power distribution
.br
	\-i D50		# Illuminant D50  -  CIE D50 spectral power distribution (computed)
.br
	\-i D55		# Illuminant D55  -  CIE D55 spectral power distribution (computed)
.br
	\-i D65		# Illuminant D65  -  CIE D65 spectral power distribution
.br
	\-i D75		# Illuminant D75  -  CIE D75 spectral power distribution (computed)
.br
	\-i D93		# Illuminant D93  -  CIE D93 spectral power distribution (computed)
.br
.TP
Spectral Input Graph
\fBoyranos-profile-graph\fR \-s \fIFILE\fR [\-t \fINUMBER\fR] [\-b] [\-g] [\-w \fINUMBER\fR] [\-R] [\-o \fI-|FILE\fR] [\-f \fIFORMAT\fR|\-p \fIFORMAT\fR] [\-v]
.br
\-s|\-\-spectral \fIFILE\fR	Spectral Input
.br
\-p|\-\-spectral-format \fIFORMAT\fR	Specify spectral output file format
.br
	\-p png		# PNG  -  PNG Raster
.br
	\-p svg		# SVG  -  SVG Vector
.br
	\-p csv		# CSV  -  CSV Values
.br
	\-p ncc		# NCC  -  Named Color Collection
.br
	\-p cgast		# CGATS  -  CGATS Values
.br
	\-p ppm		# PPM  -  Spectral PAM Image
.br
.TP
General options
.br
\-t|\-\-thickness \fINUMBER\fR	Specify the thickness of the graph lines (NUMBER:1 [≥0.0001 ≤10])
.br
\-b|\-\-no-border	Omit border in graph
.br
\-g|\-\-no-color	Draw Gray
.br
\-w|\-\-width \fINUMBER\fR	Specify output image width in pixel (NUMBER:128 [≥64 ≤4096])
.br
\-R|\-\-raster	Draw Raster
.br
\-o|\-\-output \fI-|FILE\fR	Specify output file name, default is stdout
.br
\-f|\-\-format \fIFORMAT\fR	Specify output file format png or svg, default is png
.br
	\-f png		# PNG  -  PNG Raster
.br
	\-f svg		# SVG  -  SVG Vector
.br
\-X|\-\-export \fIjson|json+command|man|markdown\fR	Export formated text: Get UI converted into text formats
.br
	\-X json		# Json  -  Get a Oyjl Json UI declaration
.br
	\-X json+command		# Json + Command  -  Get Oyjl Json UI declaration incuding command
.br
	\-X man		# Man  -  Get a unix man page
.br
	\-X markdown		# Markdown  -  Get formated text
.br
\-v|\-\-verbose	verbose
.br
\-h|\-\-help	Help
.br
.SH ENVIRONMENT VARIABLES
.TP
OY_DEBUG
.br
set the Oyranos debug level. Alternatively the -v option can be used. Valid integer range is from 1-20.
.TP
XDG_DATA_HOME XDG_DATA_DIRS
.br
route Oyranos to top directories containing resources. The derived paths for ICC profiles have a "color/icc" appended. http://www.oyranos.com/wiki/index.php?title=OpenIccDirectoryProposal  
.SH EXAMPLES
.TP
Show graph of a ICC profile
.br
oyranos-profile-graph ICC_PROFILE 
.TP
Show the saturation lines of two profiles in CIE*ab 256 pixel width, without spectral line and with thicker lines:
.br
oyranos-profile-graph -w 256 -s -t 3 sRGB.icc ProPhoto-RGB.icc 
.TP
Show the standard observer spectral function as curves:
.br
oyranos-profile-graph --standard-observer -o CIE-StdObserver.png 
.SH AUTHOR
Kai-Uwe Behrmann http://www.oyranos.org
.SH COPYRIGHT
Copyright 2018 Kai-Uwe Behrmann
.br
License: newBSD
.SH BUGS
https://www.github.com/oyranos-cms/oyranos/issues 

