.TH "oyranos-profile-graph" 1 "March 24, 2019" "User Commands"
.SH NAME
oyranos-profile-graph v0.9.7 \- Oyranos Profile Graph
.SH SYNOPSIS
\fBoyranos-profile-graph\fR [\fB\-t\fR \fINUMBER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMBER\fR] [\fB\-o\fR \fI-|FILE\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-c\fR] [\fB\-x\fR] [\fB\-d\fR \fINUMBER\fR] [\fB\-n\fR] [\fB\-2\fR] [\fB\-4\fR] [\fB\-r\fR] [\fB\-v\fR] l|rgb|cmyk|gray|lab|xyz|web|effect|proof|FILE
.br
\fBoyranos-profile-graph\fR \fB\-S\fR [\fB\-t\fR \fINUMBER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMBER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|FILE\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fBoyranos-profile-graph\fR \fB\-O\fR [\fB\-t\fR \fINUMBER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMBER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|FILE\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fBoyranos-profile-graph\fR \fB\-k\fR \fINUMBER\fR [\fB\-t\fR \fINUMBER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMBER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|FILE\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fBoyranos-profile-graph\fR \fB\-i\fR \fISTRING\fR [\fB\-t\fR \fINUMBER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMBER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|FILE\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fBoyranos-profile-graph\fR \fB\-s\fR \fIFILE\fR \fB\-p\fR \fIFORMAT\fR \fB\-z\fR [\fB\-t\fR \fINUMBER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMBER\fR] [\fB\-T\fR] [\fB\-P\fR \fISTRING\fR] [\fB\-o\fR \fI-|FILE\fR] [\fB\-v\fR]
.br
\fBoyranos-profile-graph\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR | \fB\-h\fR [\fB\-v\fR]
.SH DESCRIPTION
The  oyranos-profile-graph programm converts ICC profiles or embedded ICC profiles from images to a graph image. By default the program shows the saturation line of the specified profiles and writes to stdout.
.SH OPTIONS
.SS
2D Graph from profiles
\fBoyranos-profile-graph\fR [\fB\-t\fR \fINUMBER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMBER\fR] [\fB\-o\fR \fI-|FILE\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-c\fR] [\fB\-x\fR] [\fB\-d\fR \fINUMBER\fR] [\fB\-n\fR] [\fB\-2\fR] [\fB\-4\fR] [\fB\-r\fR] [\fB\-v\fR] l|rgb|cmyk|gray|lab|xyz|web|effect|proof|FILE
.br
Create a 2D Graph containing the saturation line from a ICC Profile.
.br
.sp
.br
\fIl|rgb|cmyk|gray|lab|xyz|web|effect|proof|FILE\fR	ICC Profile
.br
\fB\-d\fR|\fB\-\-change-thickness\fR \fINUMBER\fR	Specify increase of the thickness of the graph lines (NUMBER:0.7 [≥-1000 ≤1000])
.br
\fB\-x\fR|\fB\-\-xyy\fR	Use CIE*xyY *x*y plane for saturation line projection
.br
\fB\-c\fR|\fB\-\-no-blackbody\fR	Omit white line of lambert light emitters
.br
\fB\-n\fR|\fB\-\-no-spectral-line\fR	Omit the spectral line
.br
\fB\-2\fR|\fB\-\-icc-version-2\fR	Select ICC v2 Profiles
.br
\fB\-4\fR|\fB\-\-icc-version-4\fR	Select ICC v4 Profiles
.br
\fB\-r\fR|\fB\-\-no-repair\fR	No Profile repair of ICC profile ID
.br
.SS
Standard Observer 1931 2° Graph
\fBoyranos-profile-graph\fR \fB\-S\fR [\fB\-t\fR \fINUMBER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMBER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|FILE\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fB\-S\fR|\fB\-\-standard-observer\fR	CIE Standard Observer 1931 2°
.br
.SS
1964 10° Observer Graph
\fBoyranos-profile-graph\fR \fB\-O\fR [\fB\-t\fR \fINUMBER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMBER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|FILE\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fB\-O\fR|\fB\-\-observer-64\fR	CIE Observer 1964 10°
.br
.SS
Blackbody Radiator Spectrum Graph
\fBoyranos-profile-graph\fR \fB\-k\fR \fINUMBER\fR [\fB\-t\fR \fINUMBER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMBER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|FILE\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fB\-k\fR|\fB\-\-kelvin\fR \fINUMBER\fR	Blackbody Radiator (NUMBER:0 [≥0 ≤25000])
.br
.SS
Illuminant Spectrum Graph
\fBoyranos-profile-graph\fR \fB\-i\fR \fISTRING\fR [\fB\-t\fR \fINUMBER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMBER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|FILE\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fB\-i\fR|\fB\-\-illuminant\fR \fISTRING\fR	Illuminant Spectrum
.br
	\-i A		# Illuminant A 
.br
	 CIE A spectral power distribution
.br
	\-i D50		# Illuminant D50 
.br
	 CIE D50 spectral power distribution (computed)
.br
	\-i D55		# Illuminant D55 
.br
	 CIE D55 spectral power distribution (computed)
.br
	\-i D65		# Illuminant D65 
.br
	 CIE D65 spectral power distribution (computed)
.br
	\-i D65T		# Illuminant D65 T 
.br
	 CIE D65 spectral power distribution
.br
	\-i D75		# Illuminant D75 
.br
	 CIE D75 spectral power distribution (computed)
.br
	\-i D93		# Illuminant D93 
.br
	 CIE D93 spectral power distribution (computed)
.br
.SS
Spectral Input Graph
\fBoyranos-profile-graph\fR \fB\-s\fR \fIFILE\fR \fB\-p\fR \fIFORMAT\fR \fB\-z\fR [\fB\-t\fR \fINUMBER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMBER\fR] [\fB\-T\fR] [\fB\-P\fR \fISTRING\fR] [\fB\-o\fR \fI-|FILE\fR] [\fB\-v\fR]
.br
\fB\-s\fR|\fB\-\-spectral\fR \fIFILE\fR	Spectral Input
.br
\fB\-p\fR|\fB\-\-spectral-format\fR \fIFORMAT\fR	Specify spectral output file format
.br
	\-p png		# PNG 
.br
	 PNG Raster
.br
	\-p svg		# SVG 
.br
	 SVG Vector
.br
	\-p csv		# CSV 
.br
	 CSV Values
.br
	\-p ncc		# NCC 
.br
	 Named Color Collection
.br
	\-p cgats		# CGATS 
.br
	 CGATS Values
.br
	\-p icc-xml		# Icc XML 
.br
	 ICC Named Color Values
.br
	\-p ppm		# PPM 
.br
	 Spectral PAM Image
.br
\fB\-P\fR|\fB\-\-pattern\fR \fISTRING\fR	Filter of Color Names
.br
\fB\-z\fR|\fB\-\-scale\fR	Scale the height of the spectrum graph
.br
.SS
General options
\fBoyranos-profile-graph\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR | \fB\-h\fR [\fB\-v\fR]
.br
\fB\-t\fR|\fB\-\-thickness\fR \fINUMBER\fR	Specify the thickness of the graph lines (NUMBER:1 [≥0 ≤10])
.br
\fB\-b\fR|\fB\-\-no-border\fR	Omit border in graph
.br
\fB\-g\fR|\fB\-\-no-color\fR	Draw Gray
.br
\fB\-w\fR|\fB\-\-width\fR \fINUMBER\fR	Specify output image width in pixel (NUMBER:128 [≥64 ≤4096])
.br
\fB\-T\fR|\fB\-\-raster\fR	Draw Raster
.br
\fB\-o\fR|\fB\-\-output\fR \fI-|FILE\fR	Specify output file name, default is stdout
.br
\fB\-f\fR|\fB\-\-format\fR \fIFORMAT\fR	Specify output file format png or svg, default is png
.br
	\-f png		# PNG 
.br
	 PNG Raster
.br
	\-f svg		# SVG 
.br
	 SVG Vector
.br
\fB\-h\fR|\fB\-\-help\fR	Help
.br
\fB\-X\fR|\fB\-\-export\fR \fIjson|json+command|man|markdown\fR	Export formated text
.RS
Get UI converted into text formats
.RE
	\-X man		# Man 
.br
	 Get a unix man page
.br
	\-X markdown		# Markdown 
.br
	 Get formated text
.br
	\-X json		# Json 
.br
	 Get a Oyjl Json UI declaration
.br
	\-X json+command		# Json + Command 
.br
	 Get Oyjl Json UI declaration incuding command
.br
	\-X export		# Export 
.br
	 Get UI data for developers
.br
\fB\-v\fR|\fB\-\-verbose\fR	verbose
.br
.SH ENVIRONMENT VARIABLES
.TP
OY_DEBUG
.br
set the Oyranos debug level.
.br
Alternatively the -v option can be used.
.br
Valid integer range is from 1-20.
.TP
XDG_DATA_HOME XDG_DATA_DIRS
.br
route Oyranos to top directories containing resources. The derived paths for ICC profiles have a "color/icc" appended. http://www.oyranos.com/wiki/index.php?title=OpenIccDirectoryProposal
.SH EXAMPLES
.TP
Show graph of a ICC profile
.br
oyranos-profile-graph ICC_PROFILE
.TP
Show the saturation lines of two profiles in CIE*ab 256 pixel width, without spectral line and with thicker lines:
.br
oyranos-profile-graph -w 256 -s -t 3 sRGB.icc ProPhoto-RGB.icc
.TP
Show the standard observer spectral function as curves:
.br
oyranos-profile-graph --standard-observer -o CIE-StdObserver.png
.SH SEE AS WELL
.TP
oyranos-profile(1) oyranos-config(1) oyranos-policy(1) oyranos(3)
.br
.TP
http://www.oyranos.org
.br
.SH AUTHOR
Kai-Uwe Behrmann http://www.oyranos.org
.SH COPYRIGHT
© 2005-2020 Kai-Uwe Behrmann and others
.br
License: newBSD http://www.oyranos.org
.SH BUGS
https://www.github.com/oyranos-cms/oyranos/issues 

