.TH "oyjl-args" 1 "26. Juni 2019" "User Commands"
.SH NAME
oyjl-args v1.0.0 \- Benutzerschnittstellen nach Quelltext
.SH ÜBERSICHT
\fBoyjl-args\fR \fB\-i\fR \fIDATEINAME\fR [\fB\-\-c-stand-alone\fR] [\fB\-\-completion-bash\fR] [\fB\-v\fR]
.br
\fBoyjl-args\fR \fB\-h\fR\fI[=synopsis|...]\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR \fB\-R\fR \fIgui|cli|web|...\fR \fB\-V\fR [\fB\-i\fR \fIDATEINAME\fR] [\fB\-v\fR]
.SH BESCHREIBUNG
Werkzeug um Benutzerschnittstellen in JSON von *-X export* nach Quelltext zu übertragen.
.SH OPTIONEN
.SS
Erzeuge Quelltext
\fBoyjl-args\fR \fB\-i\fR \fIDATEINAME\fR [\fB\-\-c-stand-alone\fR] [\fB\-\-completion-bash\fR] [\fB\-v\fR]
.br
\fB\-i\fR|\fB\-\-input\fR \fIDATEINAME\fR	Setze Eingabe
.RS
Für C Quelltext Ausgabe(voreingestellt) und --completion-bash Ausgabe nutze -X=export JSON. Für --render=XXX nutze -X=json JSON.
.RE
\fB\-\-c-stand-alone\fR	Erzeuge C Quelltext für oyjl_args.c Referenz.
.RS
Lasse libOyjlCore Referenz weg.
.RE
\fB\-\-completion-bash\fR	Erzeuge Bash Vervollständigungsskript
.br
.SS
Allgemeine Optionen
\fBoyjl-args\fR \fB\-h\fR\fI[=synopsis|...]\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR \fB\-R\fR \fIgui|cli|web|...\fR \fB\-V\fR [\fB\-i\fR \fIDATEINAME\fR] [\fB\-v\fR]
.br
\fB\-h\fR|\fB\-\-help\fR\fI[=synopsis|...]\fR	Zeige Hilfetext an
.RS
Zeige Benutzungsinformationen und Hinweise für das Werkzeug.
.RE
	\fB\-h\fR -		# Vollständige Hilfe : Zeige Hilfe für alle Gruppen
.br
	\fB\-h\fR synopsis		# Übersicht : Liste Gruppen - Zeige alle Gruppen mit Syntax
.br
\fB\-X\fR|\fB\-\-export\fR \fIjson|json+command|man|markdown\fR	Exportiere formatierten Text
.RS
Hole Benutzerschnittstelle als Text
.RE
	\fB\-X\fR man		# Handbuch : Unix Handbuchseite - Hole Unix Handbuchseite
.br
	\fB\-X\fR markdown		# Markdown : Formatierter Text - Hole formatierten Text
.br
	\fB\-X\fR json		# Json : GUI - Hole Oyjl Json Benutzerschnittstelle
.br
	\fB\-X\fR json+command		# Json + Kommando : GUI + Kommando - Hole Oyjl Json Benutzerschnittstelle mit Kommando
.br
	\fB\-X\fR export		# Export : Alle verfügbaren Daten - Erhalte Daten für Entwickler
.br
\fB\-R\fR|\fB\-\-render\fR \fIgui|cli|web|...\fR	Wähle Darstellung
.RS
Wähle und konfiguriere eine Ausgabeform. -R=gui wird eine grafische Ausgabe starten.
.RE
	\fB\-R\fR gui		# Gui : Zeige UI - Zeige eine interaktive grafische Benutzerschnittstelle.
.br
	\fB\-R\fR cli		# Cli : Zeige UI - Zeige Hilfstext für Benutzerschnittstelle auf der Kommandozeile.
.br
	\fB\-R\fR web		# Web : Starte Web Server - Starte lokalen Web Service für die Darstellung in einem Webbrowser
.br
	\fB\-R\fR -
.br
\fB\-V\fR|\fB\-\-version\fR	Version
.br
\fB\-v\fR|\fB\-\-verbose\fR	plaudernd
.br
.SH BEISPIELE
.TP
Wandle EntwicklerJSON nach C Quelltext
.br
oyjl-args -X export | oyjl-args -i -
.SH SIEHE AUCH
.TP
oyjl(1) oyjl-translate(1) oyjl-args-qml(1)
.br
https://codedocs.xyz/oyranos-cms/oyranos/group__oyjl.html
.SH AUTOR
Kai-Uwe Behrmann http://www.oyranos.org
.SH KOPIERRECHT
Copyright © 2017-2021 Kai-Uwe Behrmann
.br
Lizenz: newBSD http://www.oyranos.org
.SH FEHLER
https://www.github.com/oyranos-cms/oyranos/issues 

