.TH "oyjl-args-qml" 1 "May 23, 2019" "User Commands"
.SH NAME
oyjl-args-qml v1.0 \- Oyjl Args QML Viewer
.SH ÜBERSICHT
\fBoyjl-args-qml\fR \fB\-i\fR \fISTRING\fR [\fB\-c\fR \fISTRING\fR] [\fB\-o\fR \fISTRING\fR] [\fB\-v\fR]
.br
\fBoyjl-args-qml\fR \fB\-h\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR [\fB\-v\fR]
.SH BESCHREIBUNG
The tool graphicaly renders Oyjl JSON UI files using QML.
.SH OPTIONEN
.SS
QML UI
\fBoyjl-args-qml\fR \fB\-i\fR \fISTRING\fR [\fB\-c\fR \fISTRING\fR] [\fB\-o\fR \fISTRING\fR] [\fB\-v\fR]
.br
\fB\-i\fR|\fB\-\-input\fR \fISTRING\fR	JSON UI Description
.br
\fB\-c\fR|\fB\-\-command\fR \fISTRING\fR	JSON Command
.br
\fB\-o\fR|\fB\-\-output\fR \fISTRING\fR	Results JSON
.br
.SS
General options
\fBoyjl-args-qml\fR \fB\-h\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR [\fB\-v\fR]
.br
\fB\-h\fR|\fB\-\-help\fR	Help
.br
\fB\-v\fR|\fB\-\-verbose\fR	verbose
.br
\fB\-X\fR|\fB\-\-export\fR \fIjson|json+command|man|markdown\fR	Exportiere formatierten Text
.RS
Hole Benutzerschnittstelle als Text
.RE
	\-X man		# Handbuch 
.br
	 Hole Unix Handbuchseite
.br
	\-X markdown		# Markdown 
.br
	 Hole formatierten Text
.br
	\-X json		# Json 
.br
	 Hole Oyjl Json Benutzerschnittstelle
.br
	\-X json+command		# Json + Kommando 
.br
	 Hole Oyjl Json Benutzerschnittstelle mit Kommando
.br
	\-X export		# Export 
.br
	 Erhalte Daten für Entwickler
.br
.SH BEISPIELE
.TP
Load a UI JSON declaration from file
.br
oyjl-args-qml -i oyjl-ui-text.json -c oyjl-command.json
.TP
Load a UI JSON declaration from tool
.br
oyjl -X json+command | oyjl-args-qml -i - -c +
.SH SIEHE AUCH
.TP
oyjl(1) oyjl-args(1) oyjl-translate(1)
.br

