.TH "oyjl-args" 1 "26. Juni 2019" "User Commands"
.SH NAME
oyjl-args v1.0.0 \- Benutzerschnittstellen nach Quelltext
.SH ÜBERSICHT
\fBoyjl-args\fR \fB\-i\fR \fIDATEINAME\fR [\fB\-\-completion-bash\fR] [\fB\-v\fR]
.br
\fBoyjl-args\fR \fB\-h\fR \fI[synopsis|...]\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR \fB\-V\fR [\fB\-v\fR]
.SH BESCHREIBUNG
Werkzeug um Benutzerschnittstellen in JSON von *-X export* nach Quelltext zu übertragen.
.SH OPTIONEN
.SS
Erzeuge Quelltext
\fBoyjl-args\fR \fB\-i\fR \fIDATEINAME\fR [\fB\-\-completion-bash\fR] [\fB\-v\fR]
.br
\fB\-i\fR|\fB\-\-input\fR \fIDATEINAME\fR	Setze Eingabe
.br
\fB\-\-completion-bash\fR	Erzeuge Bash Vervollständigungsskript
.br
.SS
Allgemeine Optionen
\fBoyjl-args\fR \fB\-h\fR \fI[synopsis|...]\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR \fB\-V\fR [\fB\-v\fR]
.br
\fB\-h\fR|\fB\-\-help\fR \fI[synopsis|...]\fR	Zeige Hilfetext an
.RS
Zeige Benutzungsinformationen und Hinweise für das Werkzeug.
.RE
	\-h 1		# Vollständige Hilfe
.br
	\-h synopsis		# Übersicht - Zeige alle Gruppen mit Syntax
.br
	\-h Umwandlung		# Erzeuge Quelltext
.br
	\-h Verschiedenes		# Allgemeine Optionen
.br
\fB\-X\fR|\fB\-\-export\fR \fIjson|json+command|man|markdown\fR	Exportiere formatierten Text
.RS
Hole Benutzerschnittstelle als Text
.RE
	\-X man		# Handbuch - Hole Unix Handbuchseite
.br
	\-X markdown		# Markdown - Hole formatierten Text
.br
	\-X json		# Json - Hole Oyjl Json Benutzerschnittstelle
.br
	\-X json+command		# Json + Kommando - Hole Oyjl Json Benutzerschnittstelle mit Kommando
.br
	\-X export		# Export - Erhalte Daten für Entwickler
.br
\fB\-V\fR|\fB\-\-version\fR	Version
.br
\fB\-v\fR|\fB\-\-verbose\fR	plaudernd
.br
.SH BEISPIELE
.TP
Wandle EntwicklerJSON nach C Quelltext
.br
oyjl-args -X export | oyjl-args -i -
.SH SIEHE AUCH
.TP
oyjl(1) oyjl-translate(1) oyjl-args-qml(1)
.br
https://codedocs.xyz/oyranos-cms/oyranos/group__oyjl.html
.SH AUTOR
Kai-Uwe Behrmann http://www.oyranos.org
.SH KOPIERRECHT
Copyright © 2017-2020 Kai-Uwe Behrmann
.br
Lizenz: newBSD http://www.oyranos.org
.SH FEHLER
https://www.github.com/oyranos-cms/oyranos/issues 

