.TH "oyranos-profile-graph" 1 "March 24, 2019" "User Commands"
.SH NAME
oyranos-profile-graph v0.9.7 \- Oyranos Profile Zeichner
.SH ÜBERSICHT
\fBoyranos-profile-graph\fR [\-t \fINUMMER\fR] [\-b] [\-g] [\-w \fINUMMER\fR] [\-o \fI-|DATEI\fR] [\-f \fIFORMAT\fR] [\-c] [\-x] [\-d \fINUMMER\fR] [\-n] [\-2] [\-4] [\-r] [\-v] l|rgb|cmyk|gray|lab|xyz|web|effect|proof|FILE
.br
\fBoyranos-profile-graph\fR \-S [\-t \fINUMMER\fR] [\-b] [\-g] [\-w \fINUMMER\fR] [\-R] [\-o \fI-|DATEI\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\fBoyranos-profile-graph\fR \-O [\-t \fINUMMER\fR] [\-b] [\-g] [\-w \fINUMMER\fR] [\-R] [\-o \fI-|DATEI\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\fBoyranos-profile-graph\fR \-k \fINUMMER\fR [\-t \fINUMMER\fR] [\-b] [\-g] [\-w \fINUMMER\fR] [\-R] [\-o \fI-|DATEI\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\fBoyranos-profile-graph\fR \-i \fIWORT\fR [\-t \fINUMMER\fR] [\-b] [\-g] [\-w \fINUMMER\fR] [\-R] [\-o \fI-|DATEI\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\fBoyranos-profile-graph\fR \-s \fIDATEI\fR \-p \fIFORMAT\fR \-z [\-t \fINUMMER\fR] [\-b] [\-g] [\-w \fINUMMER\fR] [\-R] [\-P \fIWORT\fR] [\-o \fI-|DATEI\fR] [\-v]
.br
\fBoyranos-profile-graph\fR \-X \fIjson|json+command|man|markdown\fR | \-h [\-v]
.SH BESCHREIBUNG
Das oyranos-profile-graph Programm erzeugt aus einem ICC Profil oder eingebetteten ICC Profil in eine Grafik. Vorgabemäßig malt es die Sättigungslinie eines anzugebenden ICC Profiles und schreibt die Grafik nach stdout.
.SH OPTIONEN
.SS
2D Zeichnung vom Farbprofil
\fBoyranos-profile-graph\fR [\-t \fINUMMER\fR] [\-b] [\-g] [\-w \fINUMMER\fR] [\-o \fI-|DATEI\fR] [\-f \fIFORMAT\fR] [\-c] [\-x] [\-d \fINUMMER\fR] [\-n] [\-2] [\-4] [\-r] [\-v] l|rgb|cmyk|gray|lab|xyz|web|effect|proof|FILE
.br
Erzeuge aus einem ICC Profil eine Grafik mit seiner Sättigungslinie.
.br
.sp
.br
\fIl|rgb|cmyk|gray|lab|xyz|web|effect|proof|FILE\fR	ICC Profil
.br
\-d|\-\-change-thickness \fINUMMER\fR	Gib die Verstärkung der Liniendicke an (NUMMER:0,7 [≥-1000 ≤1000])
.br
\-x|\-\-xyy	Benutze CIE*xyY *x*y Ebene für Projektion
.br
\-c|\-\-no-blackbody	Lasse Weißlinie von Lambertstrahlern fort
.br
\-n|\-\-no-spectral-line	Lasse Spektrallinie fort
.br
\-2|\-\-icc-version-2	Wähle ICC V2 Profile
.br
\-4|\-\-icc-version-4	Wähle ICC V4 Profile
.br
\-r|\-\-no-repair	Lasse Reparatur der Profil ID weg
.br
.SS
Standard Betrachter 1931 2° Zeichnung
\fBoyranos-profile-graph\fR \-S [\-t \fINUMMER\fR] [\-b] [\-g] [\-w \fINUMMER\fR] [\-R] [\-o \fI-|DATEI\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\-S|\-\-standard-observer	CIE Standard Betrachter 1931 2°
.br
.SS
1964 10° Betrachter Zeichnung
\fBoyranos-profile-graph\fR \-O [\-t \fINUMMER\fR] [\-b] [\-g] [\-w \fINUMMER\fR] [\-R] [\-o \fI-|DATEI\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\-O|\-\-observer-64	CIE Betrachter 1064 10°
.br
.SS
Spektrumgraph eines Lambertstrahlers
\fBoyranos-profile-graph\fR \-k \fINUMMER\fR [\-t \fINUMMER\fR] [\-b] [\-g] [\-w \fINUMMER\fR] [\-R] [\-o \fI-|DATEI\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\-k|\-\-kelvin \fINUMMER\fR	Lambertstrahler (NUMMER:0 [≥0 ≤25000])
.br
.SS
Beleuchtungsspektrumzeichnung
\fBoyranos-profile-graph\fR \-i \fIWORT\fR [\-t \fINUMMER\fR] [\-b] [\-g] [\-w \fINUMMER\fR] [\-R] [\-o \fI-|DATEI\fR] [\-f \fIFORMAT\fR] [\-v]
.br
\-i|\-\-illuminant \fIWORT\fR	Beleuchtungsspektrum
.br
	\-i A		# Lichtart A 
.br
	 CIE A Strahlungsverteilung
.br
	\-i D50		# Lichtart D50 
.br
	 CIE D50 Strahlungsverteilung (berechnet)
.br
	\-i D55		# Lichtart D55 
.br
	 CIE D55 Strahlungsverteilung (berechnet)
.br
	\-i D65		# Lichtart D65 
.br
	 CIE D65 Strahlungsverteilung (berechnet)
.br
	\-i D65T		# Lichtart D65 T 
.br
	 CIE D65 Strahlungsverteilung
.br
	\-i D75		# Lichtart D75 
.br
	 CIE D75 Strahlungsverteilung (berechnet)
.br
	\-i D93		# Lichtart D93 
.br
	 CIE D93 Strahlungsverteilung (berechnet)
.br
.SS
Spektrumgraph
\fBoyranos-profile-graph\fR \-s \fIDATEI\fR \-p \fIFORMAT\fR \-z [\-t \fINUMMER\fR] [\-b] [\-g] [\-w \fINUMMER\fR] [\-R] [\-P \fIWORT\fR] [\-o \fI-|DATEI\fR] [\-v]
.br
\-s|\-\-spectral \fIDATEI\fR	Spektrale Eingabe
.br
\-p|\-\-spectral-format \fIFORMAT\fR	Gib spektrales Ausgabeformat an
.br
	\-p png		# PNG 
.br
	 PNG Raster
.br
	\-p svg		# SVG 
.br
	 SVG Vektor
.br
	\-p csv		# CSV 
.br
	 CSV Werte
.br
	\-p ncc		# NCC 
.br
	 Einzelfarbsammlung (NCC)
.br
	\-p cgats		# CGATS 
.br
	 CGATS Werte
.br
	\-p icc-xml		# Icc XML 
.br
	 ICC Einzelfarben Werte
.br
	\-p ppm		# PPM 
.br
	 Spektrales PAM Bild
.br
\-P|\-\-pattern \fIWORT\fR	Filter für Farbnamen
.br
\-z|\-\-scale	Skaliere die Höhe der Spektrumkurve
.br
.SS
Allgemeine Optionen
\fBoyranos-profile-graph\fR \-X \fIjson|json+command|man|markdown\fR | \-h [\-v]
.br
\-t|\-\-thickness \fINUMMER\fR	Gib die Liniendicke an (NUMMER:1 [≥0 ≤10])
.br
\-b|\-\-no-border	Lasse Rand aus in Zeichnung
.br
\-g|\-\-no-color	Zeichne grau
.br
\-w|\-\-width \fINUMMER\fR	Gib Ausgabebildbreite in Pixel an (NUMMER:128 [≥64 ≤4096])
.br
\-R|\-\-raster	Zeichne Gitter
.br
\-o|\-\-output \fI-|DATEI\fR	Gib Ausgabedateiname an, voreingestellt ist stdout
.br
\-f|\-\-format \fIFORMAT\fR	Gib Ausgabeformat PNG oder SVG an, voreingestellt ist PNG
.br
	\-f png		# PNG 
.br
	 PNG Raster
.br
	\-f svg		# SVG 
.br
	 SVG Vektor
.br
\-h|\-\-help	Hilfe
.br
\-X|\-\-export \fIjson|json+command|man|markdown\fR	Exportiere formatierten Text
.RS
Hole Benutzerschnittstelle als Text
.RE
	\-X man		# Handbuch 
.br
	 Hole Unix Handbuchseite
.br
	\-X markdown		# Markdown 
.br
	 Hole formatierten Text
.br
	\-X json		# Json 
.br
	 Hole Oyjl Json Benutzerschnittstelle
.br
	\-X json+command		# Json + Kommando 
.br
	 Hole Oyjl Json Benutzerschnittstelle mit Kommando
.br
	\-X export		# Export 
.br
	 Erhalte Daten für Entwickler
.br
\-v|\-\-verbose	plaudernd
.br
.SH UMGEBUNGSVARIABLEN
.TP
OY_DEBUG
.br
Setze das Oyranos Fehlersuchniveau. Die -v Option kann alternativ benutzt werden. Der gültige Bereich ist 1-20.
.TP
XDG_DATA_HOME XDG_DATA_DIRS
.br
route Oyranos to top directories containing resources. The derived paths for ICC profiles have a "color/icc" appended. http://www.oyranos.com/wiki/index.php?title=OpenIccDirectoryProposal  
.SH BEISPIELE
.TP
Zeichne ICC Profil
.br
oyranos-profile-graph ICC_PROFILE 
.TP
Zeige Sättigungslinien von zwei Profilen in CIE*ab 256 Bildpunkte breit, ohne Spectrallinie und mit dickeren Linien:
.br
oyranos-profile-graph -w 256 -s -t 3 sRGB.icc ProPhoto-RGB.icc 
.TP
Zeige die Standard Betrachter Spektralfunktion als Kurven:
.br
oyranos-profile-graph --standard-observer -o CIE-StdObserver.png 
.SH AUTOR
Kai-Uwe Behrmann http://www.oyranos.org
.SH KOPIERRECHT
Copyright 2018 Kai-Uwe Behrmann
.br
Lizenz: newBSD
.SH FEHLER
https://www.github.com/oyranos-cms/oyranos/issues 

