.TH "oyranos-profile-graph" 1 "March 24, 2019" "User Commands"
.SH NAME
oyranos-profile-graph v0.9.7 \- Oyranos Profile Zeichner
.SH ÜBERSICHT
\fBoyranos-profile-graph\fR [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-c\fR] [\fB\-x\fR] [\fB\-d\fR \fINUMMER\fR] [\fB\-n\fR] [\fB\-2\fR] [\fB\-4\fR] [\fB\-r\fR] [\fB\-v\fR] l|rgb|cmyk|gray|lab|xyz|web|effect|proof|FILE
.br
\fBoyranos-profile-graph\fR \fB\-l\fR \fINUMMER\fR [\fIl|rgb|cmyk|gray|lab|xyz|web|effect|proof|FILE\fR] [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-2\fR] [\fB\-4\fR] [\fB\-r\fR] [\fB\-v\fR]
.br
\fBoyranos-profile-graph\fR \fB\-S\fR [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fBoyranos-profile-graph\fR \fB\-O\fR [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fBoyranos-profile-graph\fR \fB\-k\fR \fINUMMER\fR [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fBoyranos-profile-graph\fR \fB\-i\fR \fIWORT\fR [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fBoyranos-profile-graph\fR \fB\-s\fR \fIDATEI\fR \fB\-p\fR \fIFORMAT\fR \fB\-z\fR [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-T\fR] [\fB\-P\fR \fIWORT\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-v\fR]
.br
\fBoyranos-profile-graph\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR | \fB\-h\fR [\fB\-v\fR]
.SH BESCHREIBUNG
Das oyranos-profile-graph Programm erzeugt aus einem ICC Profil oder eingebetteten ICC Profil in eine Grafik. Vorgabemäßig malt es die Sättigungslinie eines anzugebenden ICC Profiles und schreibt die Grafik nach stdout.
.SH OPTIONEN
.SS
2D Zeichnung vom Farbprofil
\fBoyranos-profile-graph\fR [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-c\fR] [\fB\-x\fR] [\fB\-d\fR \fINUMMER\fR] [\fB\-n\fR] [\fB\-2\fR] [\fB\-4\fR] [\fB\-r\fR] [\fB\-v\fR] l|rgb|cmyk|gray|lab|xyz|web|effect|proof|FILE
.br
Erzeuge aus einem ICC Profil eine Grafik mit seiner Sättigungslinie.
.br
.sp
.br
\fIl|rgb|cmyk|gray|lab|xyz|web|effect|proof|FILE\fR	ICC Profil
.br
\fB\-d\fR|\fB\-\-change-thickness\fR \fINUMMER\fR	Gib die Verstärkung der Liniendicke an (NUMMER:0,7 [≥-1000 ≤1000])
.br
\fB\-x\fR|\fB\-\-xyy\fR	Benutze CIE*xyY *x*y Ebene für Projektion
.br
\fB\-c\fR|\fB\-\-no-blackbody\fR	Lasse Weißlinie von Lambertstrahlern fort
.br
\fB\-n\fR|\fB\-\-no-spectral-line\fR	Lasse Spektrallinie fort
.br
\fB\-2\fR|\fB\-\-icc-version-2\fR	Wähle ICC V2 Profile
.br
\fB\-4\fR|\fB\-\-icc-version-4\fR	Wähle ICC V4 Profile
.br
\fB\-r\fR|\fB\-\-no-repair\fR	Lasse Reparatur der Profil ID weg
.br
.SS
Color Patches Graph from profiles
\fBoyranos-profile-graph\fR \fB\-l\fR \fINUMMER\fR [\fIl|rgb|cmyk|gray|lab|xyz|web|effect|proof|FILE\fR] [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-2\fR] [\fB\-4\fR] [\fB\-r\fR] [\fB\-v\fR]
.br
Create a 2D Graph containing the possible color patches inside the ICC Profile gamut.
.br
.sp
.br
\fB\-l\fR|\fB\-\-hlc\fR \fINUMMER\fR	HLC Color Atlas (NUMMER:0 [≥0 ≤365])
.RS
Specify the number of Hue in the HLC color atlas in degrees and which are inside the profiles gamut. -l=365 will output all hues.
.RE
\fIl|rgb|cmyk|gray|lab|xyz|web|effect|proof|FILE\fR	ICC Profil
.br
\fB\-2\fR|\fB\-\-icc-version-2\fR	Wähle ICC V2 Profile
.br
\fB\-4\fR|\fB\-\-icc-version-4\fR	Wähle ICC V4 Profile
.br
\fB\-r\fR|\fB\-\-no-repair\fR	Lasse Reparatur der Profil ID weg
.br
.SS
Standard Betrachter 1931 2° Zeichnung
\fBoyranos-profile-graph\fR \fB\-S\fR [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fB\-S\fR|\fB\-\-standard-observer\fR	CIE Standard Betrachter 1931 2°
.br
.SS
1964 10° Betrachter Zeichnung
\fBoyranos-profile-graph\fR \fB\-O\fR [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fB\-O\fR|\fB\-\-observer-64\fR	CIE Betrachter 1064 10°
.br
.SS
Spektrumgraph eines Lambertstrahlers
\fBoyranos-profile-graph\fR \fB\-k\fR \fINUMMER\fR [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fB\-k\fR|\fB\-\-kelvin\fR \fINUMMER\fR	Lambertstrahler (NUMMER:0 [≥0 ≤25000])
.br
.SS
Beleuchtungsspektrumzeichnung
\fBoyranos-profile-graph\fR \fB\-i\fR \fIWORT\fR [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-T\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-f\fR \fIFORMAT\fR] [\fB\-v\fR]
.br
\fB\-i\fR|\fB\-\-illuminant\fR \fIWORT\fR	Beleuchtungsspektrum
.br
	\-i A		# Lichtart A - CIE A Strahlungsverteilung
.br
	\-i D50		# Lichtart D50 - CIE D50 Strahlungsverteilung (berechnet)
.br
	\-i D55		# Lichtart D55 - CIE D55 Strahlungsverteilung (berechnet)
.br
	\-i D65		# Lichtart D65 - CIE D65 Strahlungsverteilung (berechnet)
.br
	\-i D65T		# Lichtart D65 T - CIE D65 Strahlungsverteilung
.br
	\-i D75		# Lichtart D75 - CIE D75 Strahlungsverteilung (berechnet)
.br
	\-i D93		# Lichtart D93 - CIE D93 Strahlungsverteilung (berechnet)
.br
.SS
Spektrumgraph
\fBoyranos-profile-graph\fR \fB\-s\fR \fIDATEI\fR \fB\-p\fR \fIFORMAT\fR \fB\-z\fR [\fB\-t\fR \fINUMMER\fR] [\fB\-b\fR] [\fB\-g\fR] [\fB\-w\fR \fINUMMER\fR] [\fB\-T\fR] [\fB\-P\fR \fIWORT\fR] [\fB\-o\fR \fI-|DATEI\fR] [\fB\-v\fR]
.br
\fB\-s\fR|\fB\-\-spectral\fR \fIDATEI\fR	Spektrale Eingabe
.br
\fB\-p\fR|\fB\-\-spectral-format\fR \fIFORMAT\fR	Gib spektrales Ausgabeformat an
.br
	\-p png		# PNG - PNG Raster
.br
	\-p svg		# SVG - SVG Vektor
.br
	\-p csv		# CSV - CSV Werte
.br
	\-p ncc		# NCC - Einzelfarbsammlung (NCC)
.br
	\-p cgats		# CGATS - CGATS Werte
.br
	\-p icc-xml		# Icc XML - ICC Einzelfarben Werte
.br
	\-p ppm		# PPM - Spektrales PAM Bild
.br
\fB\-P\fR|\fB\-\-pattern\fR \fIWORT\fR	Filter für Farbnamen
.br
\fB\-z\fR|\fB\-\-scale\fR	Skaliere die Höhe der Spektrumkurve
.br
.SS
Allgemeine Optionen
\fBoyranos-profile-graph\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR | \fB\-h\fR [\fB\-v\fR]
.br
\fB\-t\fR|\fB\-\-thickness\fR \fINUMMER\fR	Gib die Liniendicke an (NUMMER:1 [≥0 ≤10])
.br
\fB\-b\fR|\fB\-\-no-border\fR	Lasse Rand aus in Zeichnung
.br
\fB\-g\fR|\fB\-\-no-color\fR	Zeichne grau
.br
\fB\-w\fR|\fB\-\-width\fR \fINUMMER\fR	Gib Ausgabebildbreite in Pixel an (NUMMER:128 [≥64 ≤4096])
.br
\fB\-T\fR|\fB\-\-raster\fR	Zeichne Gitter
.br
\fB\-o\fR|\fB\-\-output\fR \fI-|DATEI\fR	Gib Ausgabedateiname an, voreingestellt ist stdout
.br
\fB\-f\fR|\fB\-\-format\fR \fIFORMAT\fR	Gib Ausgabeformat PNG oder SVG an, voreingestellt ist PNG
.br
	\-f png		# PNG - PNG Raster
.br
	\-f svg		# SVG - SVG Vektor
.br
\fB\-h\fR|\fB\-\-help\fR	Hilfe
.br
\fB\-X\fR|\fB\-\-export\fR \fIjson|json+command|man|markdown\fR	Exportiere formatierten Text
.RS
Hole Benutzerschnittstelle als Text
.RE
	\-X man		# Handbuch - Hole Unix Handbuchseite
.br
	\-X markdown		# Markdown - Hole formatierten Text
.br
	\-X json		# Json - Hole Oyjl Json Benutzerschnittstelle
.br
	\-X json+command		# Json + Kommando - Hole Oyjl Json Benutzerschnittstelle mit Kommando
.br
	\-X export		# Export - Erhalte Daten für Entwickler
.br
\fB\-v\fR|\fB\-\-verbose\fR	plaudernd
.br
.SH UMGEBUNGSVARIABLEN
.TP
OY_DEBUG
.br
Setze das Oyranos Fehlersuchniveau.
.br
Die -v Option kann alternativ benutzt werden.
.br
Der gültige Bereich ist 1-20.
.TP
XDG_DATA_HOME XDG_DATA_DIRS
.br
route Oyranos to top directories containing resources. The derived paths for ICC profiles have a "color/icc" appended. http://www.oyranos.com/wiki/index.php?title=OpenIccDirectoryProposal
.SH BEISPIELE
.TP
Zeichne ICC Profil
.br
oyranos-profile-graph ICC_PROFILE
.TP
Zeige Sättigungslinien von zwei Profilen in CIE*ab 256 Bildpunkte breit, ohne Spectrallinie und mit dickeren Linien:
.br
oyranos-profile-graph -w 256 -s -t 3 sRGB.icc ProPhoto-RGB.icc
.TP
Zeige die Standard Betrachter Spektralfunktion als Kurven:
.br
oyranos-profile-graph --standard-observer -o CIE-StdObserver.png
.TP
Show the 
.br
oyranos-profile-graph -c -o CIE-StdObserver.png
.SH SIEHE AUCH
.TP
oyranos-profile(1) oyranos-config(1) oyranos-policy(1) oyranos(3)
.br
.TP
http://www.oyranos.org
.br
.SH AUTOR
Kai-Uwe Behrmann http://www.oyranos.org
.SH KOPIERRECHT
© 2005-2020 Kai-Uwe Behrmann and others
.br
Lizenz: newBSD http://www.oyranos.org
.SH FEHLER
https://www.github.com/oyranos-cms/oyranos/issues 

