.TH "oyranos-xforms-fltk" 1 "July 08, 2011" "User Commands"
.SH NAME
oyranos-xforms-fltk \- Oyranos option forms GUI
.SH SYNOPSIS
\fBoyranos-xforms-fltk\fR [ [-i \fIFILENAME\fR] [-v] [-o \fIFILENAME\fR] ]
.fi
\fBoyranos-xforms-fltk\fR [-?]
.SH DESCRIPTION
The tool show a configuration of a Oyranos forms in a GUI.
.SH OPTIONS
.TP
.B \-i \fIo(X)FORMS.xhtml\fR
Select the input forms file.

\fB-o\fR \fIFILENAME\fR
Dump the new model to a options form document.

\fB-v\fR be verbose
.TP
.B \-?
help text
.SH ENVIRONMENT
.TP
.B OY_DEBUG
set the Oyranos debug level. Alternatively the -v option can be used.
.TP
.B XDG_CONFIG_HOME XDG_DATA_DIRS
route Oyranos to top directories containing resources. The derived paths for
policies have a "color/settings" appended.
.nf
http://www.oyranos.com/wiki/index.php?title=OpenIccDirectoryProposal
.TP
.B OY_MODULE_PATH
route Oyranos to additional directories containing modules.
.SH EXAMPLES
.TP
Pipe in forms, show and write to file:
.B oyranos-xforms-modules -n lcms2 | oyranos-xforms-fltk -o lcms2.xhtml
.TP
Print a help text:
.B oyranos-xforms-fltk -?
.PP
.SH AUTHOR
Kai-Uwe Behrmann (ku.b (at) gmx.de)
.SH COPYRIGHT
(c) 2005-2011, Kai-Uwe Behrmann and others
.fi
License: new BSD <http://www.opensource.org/licenses/BSD-3-Clause>
.SH "SEE ALSO"
oyranos-config(3) oyranos-policy(1) oyranos(3) oyranos-xforms(1) oyranos-xforms-modules
.fi
http://www.oyranos.org
.SH "BUGS"
at: http://sourceforge.net/tracker/?group_id=177017&atid=879553
