.TH "oyranos-xforms-modules" 1 "April 24, 2013" "User Commands"
.SH NAME
oyranos-xforms-modules \- Oyranos command line option forms dumping tool
.SH SYNOPSIS
\fBoyranos-xforms-modules\fR [ [-n \fIREGISTRATION\fR] [-x \fIFILENAME\fR] [-v] ]
.fi
\fBoyranos-xforms-modules\fR [ [-n \fIREGISTRATION\fR -t \fITYPE\fR] [--short [--short]] [-v] ]
.fi
\fBoyranos-xforms-modules\fR [-l]
.fi
\fBoyranos-xforms-modules\fR [-?]
.SH DESCRIPTION
The tool dumps out Oyranos option forms from a given module.
.SH OPTIONS
.TP
.B \-n \fImodule_registration\fR
Get option forms from module.

\fB-f\fR include policy options

\fB-x\fR \fIFILENAME\fR
Write to a option forms document.
.TP
.B \-n \fImodule_registration\fR \-t \fItype\fR
Get informations from module.

\fB-t\fR  \fI""\fR list information types

\fB-t\fR  \fIname\fR get informations of type "name"

\fB--short\fR make information shorter,

\fB--short --short\fR gives a nick length information
.TP
.B \-l list modules registrations
.TP
.B \-v be verbose
.TP
.B \-?
help text
.SH ENVIRONMENT
.TP
.B OY_DEBUG
set the Oyranos debug level. Alternatively the -v option can be used.
.TP
.B XDG_CONFIG_HOME XDG_DATA_DIRS
route Oyranos to top directories containing resources. The derived paths for
policies have a "color/settings" appended.
.nf
http://www.openicc.info/index.php%3ftitle=OpenIccDirectoryProposal.html
.TP
.B OY_MODULE_PATH
route Oyranos to additional directories containing modules.
.SH EXAMPLES
.TP
Get default options forms for module:
.B oyranos-xforms-modules -n lcm2
.TP
Get default options forms for module and write to a file:
.B oyranos-xforms-modules -n lcm2 -x lcms.xhtml
.TP
Pipe in forms, show and write to file:
.B oyranos-xforms-modules -n lcm2 | oyranos-xforms-fltk -o lcm2.xhtml
.TP
Get help text for module:
.B oyranos-xforms-modules -n 4_scale -t help
.TP
Print a help text:
.B oyranos-xforms-modules -?
.PP
.SH MODULE SELECTION
.TP
The -n module / filter selection happens as string called a registration. Fro instance "org/oyranos/openicc/icc_color._lcm2._CPU._NOACCEL"
This is how Oyranos identifies filters. The string is separated into sections by a slash'/'.
The sections can be subdivided by point'.' for additional attributes as needed.
.TP
The sections meaning are as follows:

.B  top
e.g. org

.B  vendor
e.g. oyranos

.B  filter type
e.g. openicc

.B  filter name
e.g. "icc_color._lcm2._NOACCEL._CPU"
.TP
Registration search pattern:
To explicitely select a different processor and context creator the according registration attribute must have a number and prefix, e.g. "4_lcms" "7_octl". A search pattern can add keywords.

a number followed by underscore, plus or minus signs the according API. The feature of interesst must then be appended, e.g. "7_GPU" preferes a GPU interpolator. This is useful to select a certain API of a module.
            underscore '_' means preference
            minus '-' means must skip
            plus '+' means must have
        "4[_,+,-]" - context+UI oyCMMapi4_s
        "6[_,+,-]" - context convertor oyCMMapi6_s
        "7[_,+,-]" - processor oyCMMapi7_s
By default all attributes in a search pattern are considered mandatory. A level can be omitted, "//", or a attribute can be tagged by a '_' underscore in front for making it optional, or a '-' to indicate a attibute must not match.

Example - a complete registration search pattern:

"//openicc/4+icc_color.7+ACCEL.7_GPU.7_HLSL.7-GLSL" selects a accelerated CMM interpolator with prefered GPU and HLSL but no GLSL support together with a ICC compliant context generator and options.

"//openicc/4_lcms.7_lcm2" selects the "lcms" options filter together with a "lcm2" data processor
.PP
.SH AUTHOR
Kai-Uwe Behrmann (ku.b (at) gmx.de)
.SH COPYRIGHT
(c) 2005-2011, Kai-Uwe Behrmann and others
.fi
License: new BSD <http://www.opensource.org/licenses/BSD-3-Clause>
.SH "SEE ALSO"
oyranos-config(3) oyranos-policy(1) oyranos(3) oyranos-xforms(1) oyranos-xforms-fltk(1)
.fi
http://www.oyranos.org
.SH "BUGS"
at: http://sourceforge.net/tracker/?group_id=177017&atid=879553
