// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include <fl_i18n.H>
#include "fl_i18n_example.h"
#include <FL/fl_draw.H>//#include "fl_i18n.H"
#include <cstdio>

void MyBox::draw() {
  fl_font( FL_HELVETICA, 24);
  
  int tw,th;
  fl_measure("Hallo", tw, th);

  fl_draw( _("Hello, world!"), x() + 10, y() + 5 + th );
}

MyBox::MyBox( int x, int y, int w, int h, const char *label): Fl_Box(x,y,w,h,label) {
}

MyBox::MyBox( int x, int y, int w, int h ): Fl_Box(x,y,w,h) {
}

MyBox *b=(MyBox *)0;

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  const char *locale_paths[1] = {"./po"};
  const char *domain = {"fl_i18n"};

  fl_font( FL_HELVETICA, 24);
  fl_font( FL_COURIER, 24);
  printf("%s %s\n", Fl::get_font((Fl_Font)0), Fl::get_font_name((Fl_Font)0,0));

  if ( fl_search_locale_path  ( 1,
                                locale_paths,
                                "de",
                                domain) >= 0 )
  {
#if defined(_Xutf8_h) || HAVE_FLTK_UTF8
    int set_charset = 0;
#else
    int set_charset = 1;
#endif
    int err = fl_initialise_locale ( domain, locale_paths[0],
                                     set_charset );
    if(err) {
      printf("i18n initialisation failed");
    } else
      printf("Locale found in %s\n", locale_paths[0]);
  } else
    printf("Locale not found in %s\n", locale_paths[0]);

  printf("%s\n",_("Hello, world!"));
  { Fl_Double_Window* o = new Fl_Double_Window(238, 133, _("fl_i18n_example"));
    w = o;
    { new Fl_Button(25, 61, 190, 69, _("Hello, world!"));
    } // Fl_Button* o
    { b = new MyBox(25, 2, 190, 58);
      b->box(FL_FLAT_BOX);
      b->color(FL_BACKGROUND_COLOR);
      b->selection_color(FL_BACKGROUND_COLOR);
      b->labeltype(FL_NORMAL_LABEL);
      b->labelfont(0);
      b->labelsize(14);
      b->labelcolor(FL_FOREGROUND_COLOR);
      b->align(FL_ALIGN_CENTER);
      b->when(FL_WHEN_RELEASE);
    } // MyBox* b
    o->end();
  } // Fl_Double_Window* o
  /*fl_font( FL_COURIER, 24);
  
  int tw,th;
  fl_meashure("Hallo", &tw, &th);

  fl_draw( "Hello, world!", b->x()+10, b->y()+20 + th );*/
  w->show(argc, argv);
  return Fl::run();
}
