// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include <fl_i18n.H>
#include "fl_i18n_example.h"
#include <FL/fl_draw.H>//#include "fl_i18n.H"
#include <cstdio>

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  const char *locale_paths[1] = {"./po"};
  const char *domain = {"fl_i18n"};

  fl_font( FL_COURIER, 14);

  if ( fl_search_locale_path  ( 1,
                                locale_paths,
                                "de",
                                domain) >= 0 )
  {
    fl_initialise_locale( domain, locale_paths[0] );
    printf("Locale found in %s\n", locale_paths[0]);
  } else
    printf("Locale not found in %s\n", locale_paths[0]);

  printf("%s\n",_("Hello, world!"));
  { Fl_Double_Window* o = new Fl_Double_Window(238, 133, _("fl_i18n_example"));
    w = o;
    new Fl_Button(25, 25, 190, 80, _("Hello, world!"));
    o->end();
  }
  w->show(argc, argv);
  return Fl::run();
}
