// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef fl_i18n_example_h
#define fl_i18n_example_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#endif
