.TH "openicc-device" 1 "" "User Commands"
.SH NAME
openicc-device v0.1.1 \- OpenICC Device
.SH SYNOPSIS
\fBopenicc-device\fR \fB\-l\fR [\fB\-d\fR \fINUMBER\fR] [\fB\-j\fR] [\fB\-n\fR] [\fB\-b\fR \fIFILENAME\fR] [\fB\-v\fR]
.br
\fBopenicc-device\fR \fB\-a\fR \fB\-f\fR \fIFILENAME\fR [\fB\-b\fR \fIFILENAME\fR] [\fB\-v\fR]
.br
\fBopenicc-device\fR \fB\-e\fR \fB\-d\fR \fINUMBER\fR [\fB\-b\fR \fIFILENAME\fR] [\fB\-v\fR]
.br
\fBopenicc-device\fR \fB\-p\fR [\fB\-s\fR] [\fB\-v\fR]
.br
\fBopenicc-device\fR \fB\-h\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR [\fB\-v\fR]
.SH DESCRIPTION
Manipulation of OpenICC color management data base device entries.
.SH OPTIONS
.SS
Print the Devices in the DB
\fBopenicc-device\fR \fB\-l\fR [\fB\-d\fR \fINUMBER\fR] [\fB\-j\fR] [\fB\-n\fR] [\fB\-b\fR \fIFILENAME\fR] [\fB\-v\fR]
.br
\fB\-l\fR|\fB\-\-list-devices\fR	List Devices
.br
\fB\-d\fR|\fB\-\-device\fR \fINUMBER\fR	Device position (NUMBER:0 [≥0 ≤100 Δ1])
.br
\fB\-j\fR|\fB\-\-dump-json\fR	Dump OpenICC JSON
.br
\fB\-n\fR|\fB\-\-long\fR	List all key/values pairs
.br
\fB\-b\fR|\fB\-\-db-file\fR \fIFILENAME\fR	DB File Name
.RS
File Name of OpenICC Device Data Base JSON
.RE
.SS
Add Device to DB
\fBopenicc-device\fR \fB\-a\fR \fB\-f\fR \fIFILENAME\fR [\fB\-b\fR \fIFILENAME\fR] [\fB\-v\fR]
.br
\fB\-a\fR|\fB\-\-add\fR	Add Device to DB
.br
\fB\-f\fR|\fB\-\-file-name\fR \fIFILENAME\fR	File Name
.RS
The File Name of the OpenICC Device in Json format.
.RE
\fB\-b\fR|\fB\-\-db-file\fR \fIFILENAME\fR	DB File Name
.RS
File Name of OpenICC Device Data Base JSON
.RE
.SS
Erase a Devices from the DB
\fBopenicc-device\fR \fB\-e\fR \fB\-d\fR \fINUMBER\fR [\fB\-b\fR \fIFILENAME\fR] [\fB\-v\fR]
.br
\fB\-e\fR|\fB\-\-erase-device\fR	Erase Devices
.br
\fB\-d\fR|\fB\-\-device\fR \fINUMBER\fR	Device position (NUMBER:0 [≥0 ≤100 Δ1])
.br
\fB\-b\fR|\fB\-\-db-file\fR \fIFILENAME\fR	DB File Name
.RS
File Name of OpenICC Device Data Base JSON
.RE
.SS
Show Filepath to the DB
\fBopenicc-device\fR \fB\-p\fR [\fB\-s\fR] [\fB\-v\fR]
.br
\fB\-p\fR|\fB\-\-show-path\fR	Show Path
.br
\fB\-s\fR|\fB\-\-system\fR	Local System
.br
.SS
General options
\fBopenicc-device\fR \fB\-h\fR \fB\-X\fR \fIjson|json+command|man|markdown\fR [\fB\-v\fR]
.br
\fB\-b\fR|\fB\-\-db-file\fR \fIFILENAME\fR	DB File Name
.RS
File Name of OpenICC Device Data Base JSON
.RE
\fB\-X\fR|\fB\-\-export\fR \fIjson|json+command|man|markdown\fR	Export formated text
.RS
Get UI converted into text formats
.RE
	\fB\-X\fR man		# Man : Unix Man page - Get a unix man page
.br
	\fB\-X\fR markdown		# Markdown : Formated text - Get formated text
.br
	\fB\-X\fR json		# Json : GUI - Get a Oyjl Json UI declaration
.br
	\fB\-X\fR json+command		# Json + Command : GUI + Command - Get Oyjl Json UI declaration incuding command
.br
	\fB\-X\fR export		# Export : All available data - Get UI data for developers
.br
\fB\-v\fR|\fB\-\-verbose\fR	verbose
.br
\fB\-h\fR|\fB\-\-help\fR	Help
.br
.SH AUTHOR
Kai-Uwe Behrmann http://www.openicc.org
.SH COPYRIGHT
Copyright 2018 Kai-Uwe Behrmann
.br
License: newBSD http://www.openicc.org
.SH BUGS
https://www.github.com/OpenICC/config/issues 

