.TH "oyjl-args" 1 "June 26, 2019" "User Commands"
.SH NAME
oyjl-args v1.0.0 \- Ui to source code
.SH SYNOPSIS
\fBoyjl-args\fR \fB\-i\fR \fIFILENAME\fR [\fB\-v\fR]
.br
\fBoyjl-args\fR \fB\-h\fR [\fB\-v\fR]
.SH DESCRIPTION
Tool to convert UI JSON description from *-X export* into source code.
.SH OPTIONS
.SS
Generate source code
\fBoyjl-args\fR \fB\-i\fR \fIFILENAME\fR [\fB\-v\fR]
.br
\fB\-i\fR|\fB\-\-input\fR \fIFILENAME\fR	Set Input
.br
.SS
General options
\fBoyjl-args\fR \fB\-h\fR [\fB\-v\fR]
.br
\fB\-h\fR|\fB\-\-help\fR	Help
.br
\fB\-v\fR|\fB\-\-verbose\fR	verbose
.br
.SH EXAMPLES
.TP
Convert eXported developer JSON to C source
.br
oyjl-args -X export | oyjl-args -i -
.SH SEE ALSO
.TP
oyjl(1) oyjl-translate(1) oyjl-args-qml(1)
.br
https://codedocs.xyz/oyranos-cms/oyranos/group__oyjl.html
.SH AUTHOR
Kai-Uwe Behrmann http://www.oyranos.org
.SH COPYRIGHT
Copyright © 2017-2020 Kai-Uwe Behrmann
.br
License: newBSD http://www.oyranos.org
.SH BUGS
https://www.github.com/oyranos-cms/oyranos/issues 

