.TH oyranos-image-display 1 "April 05, 2017" "User Commands"
.SH NAME
oyranos-image-display \- Oyranos color managed image viewer
.SH SYNOPSIS
\fBoyranos-image-display\fR \fIIMAGEFILENAME\fR [--no-logo] [--icc-color-context] [--use-no-gl|--shader \fIFILENAME\fR] [-v]
.SH DESCRIPTION
The oyranos-image-display is a example image viewer. It loads images, does multi monitor color correction and provides very basic view options like moving and scaling. The viewer uses the Oyranos preferences as can be edited with oyranos-config-fltk, Synnefo or on the command line through oyranos-policy or oyranos-monitor.
.SH OPTIONS
.TP
\fIIMAGEFILENAME\fR  view image
Open the image view with a specified and supported image file. Supported fromats should include PPM, PNG and CameraRAW. Optional JPEG and Tiff are supported.
.sp
.br
\fB\--no-logo\fR
skip the logo part of the viewer.
.br
\fB\--icc-color-context\fR \fICMMNAME\fR
select a CMM as listed by oyranos-xforms-modules -l. Use the oyCMMapi4_s Filter org/oyranos/openicc/icc_color registration strings. By default 'lcms' or 'lcm2' should be available.
.br
\fB\--shader\fR \fIFILENAME\fR
set a CLUT from PPM image for color transform. "oyranos-icc -f clut" can produce suitable 3D color textures.
.br
\fB\--use-no-gl\fR
use pixel copy, no OpenGL
.TP
\fB\--help\fR  
print text and exit
.SH GENERAL OPTIONS
.br
.B \-v, \-\-verbose\fR
increase verbosity
.br
.SH SHORT CUTS
.br
.B Ctrl-E\fR
edit rendering options.
.TP
.B Ctrl-I\fR
show the image profile in ICC Examin.
.TP
.B Ctrl-Q\fR
quit the viewer.
.br
.SH ENVIRONMENT
.TP
.B DISPLAY
On X11 systems the display is selected by this variable.
.TP
.B OY_DEBUG
set the Oyranos debug level. Alternatively the -v option can be used.
.TP
.B XDG_DATA_HOME XDG_DATA_DIRS
route Oyranos to top directories containing resources. The derived paths for
ICC profiles have a "color/icc" appended.
.nf
http://www.oyranos.com/wiki/index.php?title=OpenIccDirectoryProposal
.TP
.B OY_MODULE_PATH
route Oyranos to additional directories containing modules.
.SH EXAMPLES
.TP
View an image:
.B oyranos-image-display --no-logo image.ppm
.PP
.PP
.SH AUTHOR
Kai-Uwe Behrmann (ku.b (at) gmx.de)
.SH COPYRIGHT
(c) 2005-2015, Kai-Uwe Behrmann and others
.fi
License: new BSD <http://www.opensource.org/licenses/BSD-3-Clause>
.SH "SEE ALSO"
oyranos-config-fltk(1) oyranos-config-synnefo(1) oyranos-xforms-modules(1) oyranos-monitor(1) oyranos-policy(1) oyranos-xforms-fltk(1)
.fi
http://www.oyranos.org
.SH "BUGS"
at: http://sourceforge.net/p/oyranos/bugs/
